config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#index'
  resources :users 
  get 'sign_in', to: 'users#sign_in', as: 'sign_in'
  get 'sign_out', to: 'users#sign_out', as: 'sign_out'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :current_user

  def current_user
    unless session[:current_user].present?
      redirect_to sign_in_path
    end 
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  include HTTParty
  def index
    if params[:city_name].present?
      @data = HTTParty.get("https://api.openweathermap.org/data/2.5/weather?q=#{params[:city_name]}&appid=#{Rails.application.credentials.weather[:api_id]}")
    else 
      @data = nil
    end 

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :destroy]
  skip_before_action :current_user, only: [:sign_in, :sign_out]

  def index
    @users = User.all
  end

  def new
    @user = User.new   
  end

  def create
    @user = User.new(user_params)
    byebug
    if @user.save
      redirect_to root_path
    else 
      render 'new'
    end 
  end

  def edit
  
  end

  def update
    if @user.update(user_params)
      redirect_to root_path
    else 
      render 'edit'
    end 
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to(root_path, flash: {success: "User has been successfully deleted."})}
    end
  end

  def sign_in
    if params[:email].present? && params[:password].present?
      user = User.find_by_email(params[:email].strip)
      if user.password == params[:password]
        session[:current_user] = user.id
        return redirect_to root_path
      else 
        flash[:danger] = "Email/password is incorrect"
        return redirect_to :back
      end 
    end 
  end

  def sign_out
    session[:current_user] = nil
    redirect_to sign_in_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :confirm_password)
  end

  def set_user
    @user = User.find_by_id(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<div class='mt-20'>
  <p>
    Search for City weather
  </p>

  <%= form_tag root_path, :method => :get do %>
    <div class="form__group">
      <%= label_tag :city_name, "City Name"%>
      <%= text_field_tag :city_name %>
    </div>

    <%= submit_tag "Submit" %>

  <% end %>
  <% if @data.present? %>
    <div>
      <p><%= @data["weather"].first["description"] %></p>
    </div>
    <table>
      <tr>
        <th>Temperature</th>
        <th>Feels Like</th>
        <th>Min Temp</th>
        <th>Max Temp</th>
        <th>Humidity</th>
      </tr>
      <tr>
        <th><%= @data["main"]["temp"] - 273 %> | </th>
        <th><%= @data["main"]["feels_like"] - 273 %> | </th>
        <th><%= @data["main"]["temp_min"] - 273 %> | </th>
        <th><%= @data["main"]["temp_max"] - 273 %> | </th>
        <th><%= @data["main"]["humidity"] %></th>
      </tr>
    </table>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CityWeather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <div class='mt-20'>
      <p>
        <% if session[:current_user].present? %>
          <%= link_to 'Sign Out', sign_out_path%>
        <% end %>
      </p>
      <p>
        <%= link_to 'Users', users_path%>
      </p>
      <p>
        <%= link_to 'Home', root_path%>
      </p>

    </div>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class='mt-20'>
  <%= form_for @user do |f| %>
    <div class="form__group">
      <%= f.label :first_name, "First Name"%>
      <%= f.text_field :first_name %>
    </div>
    <div class="form__group">
      <%= f.label :last_name, "Last Name"%>
      <%= f.text_field :last_name %>
    </div>
    <div class="form__group">
      <%= f.label :email, "Email *"%>
      <%= f.email_field :email %>
    </div>
    <div class="form__group">
      <%= f.label :password, "Password *"%>
      <%= f.password_field :password %>
    </div>
    <div class="form__group">
      <%= f.label :confirm_password, "Confirm Password *"%>
      <%= f.text_field :confirm_password %>
    </div>

    <%= f.submit "Submit" %>

  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'form'%>

app/views/users/index.html.erb
<div class='mt-20'>  
  <table>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Edit</th>
    </tr>
    <% @users.each do |f| %>
      <tr>
        <td><%= f.first_name %></td>
        <td><%= f.last_name %></td>
        <td><%= f.email %></td>
        <td><%= link_to "edit", edit_user_path(f) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<%= render 'form'%>

app/views/users/sign_in.html.erb
<div class='mt-20'>
  <p> Sign In</p>
  <%= form_tag sign_in_path, :method => :get do %>
    <div class="form__group">
      <%= label_tag :email, "Email"%>
      <%= email_field_tag :email %>
    </div>

    <div class="form__group">
      <%= label_tag :password, "Password"%>
      <%= password_field_tag :password %>
    </div>

    <%= submit_tag "Submit" %>

  <% end %>

</div>